##
## created by Robert Jaremczak, 2024
## based on M2M work done by MJoergen and sy2002 in 2023 (GPL v3)
##

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

## pin mapping

# Onboard crystal oscillator = 100 MHz
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS33} [get_ports clk_i]

# Reset button on the side of the machine
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33} [get_ports reset_button_i]

# USB-RS232 Interface
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports uart_rxd_i]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS33} [get_ports uart_txd_o]

# VGA via VDAC. U3 = ADV7125BCPZ170
set_property -dict {PACKAGE_PIN W11 IOSTANDARD LVCMOS33} [get_ports vga_blank_n_o]
set_property -dict {PACKAGE_PIN AA9 IOSTANDARD LVCMOS33} [get_ports vga_clk_o]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports vga_psave_n_o]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports vga_sync_n_o]
set_property -dict {PACKAGE_PIN W10 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[0]}]
set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[1]}]
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[2]}]
set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[3]}]
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[4]}]
set_property -dict {PACKAGE_PIN Y11 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[5]}]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[6]}]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVCMOS33} [get_ports {vga_blue_o[7]}]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[0]}]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[1]}]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[2]}]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[3]}]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[4]}]
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[5]}]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[6]}]
set_property -dict {PACKAGE_PIN AB13 IOSTANDARD LVCMOS33} [get_ports {vga_green_o[7]}]
set_property -dict {PACKAGE_PIN W12 IOSTANDARD LVCMOS33} [get_ports vga_hs_o]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS33} [get_ports {vga_red_o[0]}]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {vga_red_o[1]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {vga_red_o[2]}]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {vga_red_o[3]}]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {vga_red_o[4]}]
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVCMOS33} [get_ports {vga_red_o[5]}]
set_property -dict {PACKAGE_PIN AA16 IOSTANDARD LVCMOS33} [get_ports {vga_red_o[6]}]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS33} [get_ports {vga_red_o[7]}]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS33} [get_ports vga_scl_io]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports vga_sda_io]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33} [get_ports vga_vs_o]

# HDMI output. U10 = PTN3363BSMP
# I2C address 0x40.
set_property -dict {PACKAGE_PIN Y1 IOSTANDARD TMDS_33} [get_ports hdmi_tmds_data_clk_n_o]
set_property -dict {PACKAGE_PIN W1 IOSTANDARD TMDS_33} [get_ports hdmi_tmds_data_clk_p_o]
set_property -dict {PACKAGE_PIN AB1 IOSTANDARD TMDS_33} [get_ports {hdmi_tmds_data_n_o[0]}]
set_property -dict {PACKAGE_PIN AB2 IOSTANDARD TMDS_33} [get_ports {hdmi_tmds_data_n_o[1]}]
set_property -dict {PACKAGE_PIN AB5 IOSTANDARD TMDS_33} [get_ports {hdmi_tmds_data_n_o[2]}]
set_property -dict {PACKAGE_PIN AA1 IOSTANDARD TMDS_33} [get_ports {hdmi_tmds_data_p_o[0]}]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD TMDS_33} [get_ports {hdmi_tmds_data_p_o[1]}]
set_property -dict {PACKAGE_PIN AA5 IOSTANDARD TMDS_33} [get_ports {hdmi_tmds_data_p_o[2]}]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports hdmi_hiz_en_o]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVCMOS33} [get_ports hdmi_hpd_i]
set_property -dict {PACKAGE_PIN AB7 IOSTANDARD LVCMOS33} [get_ports hdmi_scl_io]
set_property -dict {PACKAGE_PIN V9 IOSTANDARD LVCMOS33} [get_ports hdmi_sda_io]
set_property -dict {PACKAGE_PIN AB8 IOSTANDARD LVCMOS33} [get_ports hdmi_ls_oe_n_o]

# MEGA65 Keyboard
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports kb_io0_o]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports kb_io1_o]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports kb_io2_i]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports kb_tck_o]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS33} [get_ports kb_tdo_i]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports kb_tms_o]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports kb_tdi_o]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33} [get_ports kb_jtagen_o]

# Micro SD Connector (external slot at back of the cover)
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports sd_ext_cd_i]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports sd_ext_clk_o]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports sd_ext_miso_i]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports sd_ext_mosi_o]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports sd_ext_reset_o]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS33} [get_ports sd_ext_d1_i]
set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS33} [get_ports sd_ext_d2_i]

# SD Connector (this is the slot at the bottom side of the case under the cover)
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33} [get_ports sd_int_cd_i]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports sd_int_clk_o]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports sd_int_miso_i]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports sd_int_mosi_o]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports sd_int_reset_o]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports sd_int_wp_i]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports sd_int_d1_i]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports sd_int_d2_i]

# Audio DAC. U37 = AK4432VT
# I2C address: 0x19.
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports audio_mclk_o]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports audio_bick_o]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports audio_sdti_o]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports audio_lrclk_o]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33} [get_ports audio_pdn_n_o]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports audio_i2cfil_o]
set_property -dict {PACKAGE_PIN L6 IOSTANDARD LVCMOS33} [get_ports audio_scl_io]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD LVCMOS33} [get_ports audio_sda_io]

# Joystick
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports fa_down_n_i]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports fa_fire_n_i]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports fa_left_n_i]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports fa_right_n_i]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports fa_up_n_i]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports fb_down_n_i]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports fb_fire_n_i]
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS33} [get_ports fb_left_n_i]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports fb_right_n_i]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports fb_up_n_i]

# Paddles
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33} [get_ports paddle_drain_o]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports {paddle_i[0]}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {paddle_i[1]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {paddle_i[2]}]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVCMOS33} [get_ports {paddle_i[3]}]

# HyperRAM. U29 = IS66WVH8M8DBLL-100B1LI
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVCMOS33} [get_ports hr_clk_p_o]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33} [get_ports hr_cs0_o]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS33} [get_ports {hr_d_io[0]}]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33} [get_ports {hr_d_io[1]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports {hr_d_io[2]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports {hr_d_io[3]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {hr_d_io[4]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS33} [get_ports {hr_d_io[5]}]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS33} [get_ports {hr_d_io[6]}]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS33} [get_ports {hr_d_io[7]}]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33} [get_ports hr_reset_o]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS33} [get_ports hr_rwds_io]
set_property SLEW FAST [get_ports hr_reset_o]
set_property DRIVE 16 [get_ports hr_reset_o]
set_property SLEW FAST [get_ports hr_cs0_o]
set_property DRIVE 16 [get_ports hr_cs0_o]
set_property SLEW FAST [get_ports hr_clk_p_o]
set_property DRIVE 16 [get_ports hr_clk_p_o]
set_property SLEW FAST [get_ports {hr_d_io[7]}]
set_property SLEW FAST [get_ports {hr_d_io[6]}]
set_property SLEW FAST [get_ports {hr_d_io[5]}]
set_property SLEW FAST [get_ports {hr_d_io[4]}]
set_property SLEW FAST [get_ports {hr_d_io[3]}]
set_property SLEW FAST [get_ports {hr_d_io[2]}]
set_property SLEW FAST [get_ports {hr_d_io[1]}]
set_property SLEW FAST [get_ports {hr_d_io[0]}]
set_property DRIVE 16 [get_ports {hr_d_io[7]}]
set_property DRIVE 16 [get_ports {hr_d_io[6]}]
set_property DRIVE 16 [get_ports {hr_d_io[5]}]
set_property DRIVE 16 [get_ports {hr_d_io[4]}]
set_property DRIVE 16 [get_ports {hr_d_io[3]}]
set_property DRIVE 16 [get_ports {hr_d_io[2]}]
set_property DRIVE 16 [get_ports {hr_d_io[1]}]
set_property DRIVE 16 [get_ports {hr_d_io[0]}]
set_property PULLTYPE PULLDOWN [get_ports hr_rwds_io]
set_property SLEW FAST [get_ports hr_rwds_io]
set_property DRIVE 16 [get_ports hr_rwds_io]

# CBM-488/IEC serial port
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports iec_atn_n_o]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS33} [get_ports iec_clk_en_n_o]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports iec_clk_n_i]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports iec_clk_n_o]
set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVCMOS33} [get_ports iec_data_en_n_o]
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS33} [get_ports iec_data_n_i]
set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVCMOS33} [get_ports iec_data_n_o]
set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS33} [get_ports iec_reset_n_o]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS33} [get_ports iec_srq_en_n_o]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD LVCMOS33} [get_ports iec_srq_n_i]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports iec_srq_n_o]
set_property PULLTYPE PULLUP [get_ports iec_clk_n_i]
set_property PULLTYPE PULLUP [get_ports iec_data_n_i]

# C64 Expansion Port (aka Cartridge Port)
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports cart_phi2_o]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS33} [get_ports cart_dotclock_o]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports cart_dma_i]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports cart_reset_oe_n_o]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports cart_reset_io]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports cart_game_oe_n_o]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS33} [get_ports cart_game_io]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports cart_exrom_oe_n_o]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports cart_exrom_io]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports cart_nmi_oe_n_o]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS33} [get_ports cart_nmi_io]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports cart_irq_oe_n_o]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports cart_irq_io]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports cart_ctrl_en_o]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports cart_ctrl_dir_o]
set_property -dict {PACKAGE_PIN N13 IOSTANDARD LVCMOS33} [get_ports cart_ba_io]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports cart_rw_io]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports cart_io1_io]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS33} [get_ports cart_io2_io]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports cart_romh_oe_n_o]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports cart_romh_io]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports cart_roml_oe_n_o]
set_property -dict {PACKAGE_PIN AB18 IOSTANDARD LVCMOS33} [get_ports cart_roml_io]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports cart_en_o]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports cart_addr_en_o]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports cart_haddr_dir_o]
set_property -dict {PACKAGE_PIN L21 IOSTANDARD LVCMOS33} [get_ports cart_laddr_dir_o]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[0]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[1]}]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[2]}]
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[3]}]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[4]}]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[5]}]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[6]}]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[7]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[8]}]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[9]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[10]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[11]}]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[12]}]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[13]}]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[14]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {cart_a_io[15]}]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports cart_data_en_o]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports cart_data_dir_o]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports {cart_d_io[0]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {cart_d_io[1]}]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports {cart_d_io[2]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {cart_d_io[3]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {cart_d_io[4]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {cart_d_io[5]}]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports {cart_d_io[6]}]
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33} [get_ports {cart_d_io[7]}]

# I2C bus
# U32 = PCA9655EMTTXG. Address 0x40. I/O expander.
# U12 = MP8869SGL-Z.   Address 0x61. DC/DC Converter.
# U14 = MP8869SGL-Z.   Address 0x67. DC/DC Converter.
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports i2c_scl_io]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports i2c_sda_io]

# Debug. Also used to control output to joystick ??
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports fa_fire_n_o]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports fa_up_n_o]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports fa_left_n_o]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports fa_down_n_o]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports fb_up_n_o]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports fa_right_n_o]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports fb_down_n_o]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS33} [get_ports fb_fire_n_o]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports fb_right_n_o]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports fb_left_n_o]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports dbg_11_io]

# SMSC Ethernet PHY. U4 = KSZ8081RNDCA
set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVCMOS33} [get_ports eth_clock_o]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports eth_led2_o]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS33} [get_ports eth_mdc_o]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD LVCMOS33} [get_ports eth_mdio_io]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33} [get_ports eth_reset_o]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports {eth_rxd_i[0]}]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports {eth_rxd_i[1]}]
set_property -dict {PACKAGE_PIN K4 IOSTANDARD LVCMOS33} [get_ports eth_rxdv_i]
set_property -dict {PACKAGE_PIN M6 IOSTANDARD LVCMOS33} [get_ports eth_rxer_i]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS33} [get_ports {eth_txd_o[0]}]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports {eth_txd_o[1]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports eth_txen_o]
set_property -dict {SLEW SLOW DRIVE 4} [get_ports {eth_txd_o[*]}]
set_property -dict {SLEW SLOW DRIVE 4} [get_ports eth_txen_o]
set_property -dict {SLEW FAST} [get_ports eth_clock_o]

# FDC interface
set_property -dict {PACKAGE_PIN P6 IOSTANDARD LVCMOS33} [get_ports f_density_o]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS33} [get_ports f_diskchanged_i]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports f_index_i]
set_property -dict {PACKAGE_PIN M5 IOSTANDARD LVCMOS33} [get_ports f_motora_o]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports f_motorb_o]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVCMOS33} [get_ports f_rdata_i]
set_property -dict {PACKAGE_PIN N5 IOSTANDARD LVCMOS33} [get_ports f_selecta_o]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports f_selectb_o]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports f_side1_o]
set_property -dict {PACKAGE_PIN P5 IOSTANDARD LVCMOS33} [get_ports f_stepdir_o]
set_property -dict {PACKAGE_PIN M3 IOSTANDARD LVCMOS33} [get_ports f_step_o]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVCMOS33} [get_ports f_track0_i]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVCMOS33} [get_ports f_wdata_o]
set_property -dict {PACKAGE_PIN N3 IOSTANDARD LVCMOS33} [get_ports f_wgate_o]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVCMOS33} [get_ports f_writeprotect_i]

# I2C bus for on-board peripherals
# U36. 24AA025E48T. Address 0x50. 2K Serial EEPROM.
# U38. RV-3032-C7.  Address 0x51. Real-Time Clock Module.
# U39. 24LC128.     Address 0x56. 128K CMOS Serial EEPROM.
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports fpga_scl_io]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports fpga_sda_io]

# Connected to J18.
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33} [get_ports grove_scl_io]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33} [get_ports grove_sda_io]

# Joystick power supply
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports joystick_5v_disable_o]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports joystick_5v_powergood_i]

# On board LEDs
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports led_g_n_o]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports led_o]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports led_r_n_o]

# Pmod Header
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports {p1hi_io[0]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {p1hi_io[1]}]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports {p1hi_io[2]}]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports {p1hi_io[3]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [get_ports {p1lo_io[0]}]
set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVCMOS33} [get_ports {p1lo_io[1]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports {p1lo_io[2]}]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS33} [get_ports {p1lo_io[3]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {p2hi_io[0]}]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33} [get_ports {p2hi_io[1]}]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports {p2hi_io[2]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {p2hi_io[3]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {p2lo_io[0]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports {p2lo_io[1]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {p2lo_io[2]}]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports {p2lo_io[3]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports pmod1_en_o]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports pmod1_flag_i]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports pmod2_en_o]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports pmod2_flag_i]

# Quad SPI Flash. U5 = S25FL512SAGBHIS10
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS33} [get_ports qspicsn_o]
set_property -dict {PACKAGE_PIN P22 IOSTANDARD LVCMOS33} [get_ports {qspidb_io[0]}]
set_property -dict {PACKAGE_PIN R22 IOSTANDARD LVCMOS33} [get_ports {qspidb_io[1]}]
set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVCMOS33} [get_ports {qspidb_io[2]}]
set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVCMOS33} [get_ports {qspidb_io[3]}]
set_property PULLTYPE PULLUP [get_ports {qspidb_io[3]}]
set_property PULLTYPE PULLUP [get_ports {qspidb_io[2]}]
set_property PULLTYPE PULLUP [get_ports {qspidb_io[1]}]
set_property PULLTYPE PULLUP [get_ports {qspidb_io[0]}]

# SDRAM - 32M x 16 bit, 3.3V VCC. U44 = IS42S16320F-6BL
set_property -dict {PACKAGE_PIN T4 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[0]}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[1]}]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[2]}]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[3]}]
set_property -dict {PACKAGE_PIN Y4 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[4]}]
set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[5]}]
set_property -dict {PACKAGE_PIN W4 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[6]}]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[7]}]
set_property -dict {PACKAGE_PIN AA8 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[8]}]
set_property -dict {PACKAGE_PIN Y2 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[9]}]
set_property -dict {PACKAGE_PIN R6 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[10]}]
set_property -dict {PACKAGE_PIN Y7 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[11]}]
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS33} [get_ports {sdram_a_o[12]}]
set_property -dict {PACKAGE_PIN U3 IOSTANDARD LVCMOS33} [get_ports {sdram_ba_o[0]}]
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports {sdram_ba_o[1]}]
set_property -dict {PACKAGE_PIN V3 IOSTANDARD LVCMOS33} [get_ports sdram_cas_n_o]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS33} [get_ports sdram_cke_o]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS33} [get_ports sdram_clk_o]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS33} [get_ports sdram_cs_n_o]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[0]}]
set_property -dict {PACKAGE_PIN AA4 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[10]}]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[11]}]
set_property -dict {PACKAGE_PIN AA6 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[12]}]
set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[13]}]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[14]}]
set_property -dict {PACKAGE_PIN Y3 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[15]}]
set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[1]}]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[2]}]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[3]}]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[4]}]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[5]}]
set_property -dict {PACKAGE_PIN U6 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[6]}]
set_property -dict {PACKAGE_PIN T6 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[7]}]
set_property -dict {PACKAGE_PIN W7 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[8]}]
set_property -dict {PACKAGE_PIN AA3 IOSTANDARD LVCMOS33} [get_ports {sdram_dq_io[9]}]
set_property -dict {PACKAGE_PIN Y6 IOSTANDARD LVCMOS33} [get_ports sdram_dqmh_o]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVCMOS33} [get_ports sdram_dqml_o]
set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVCMOS33} [get_ports sdram_ras_n_o]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports sdram_we_n_o]
set_property SLEW FAST [get_ports {sdram_a_o[12]}]
set_property SLEW FAST [get_ports {sdram_a_o[11]}]
set_property SLEW FAST [get_ports {sdram_a_o[10]}]
set_property SLEW FAST [get_ports {sdram_a_o[9]}]
set_property SLEW FAST [get_ports {sdram_a_o[8]}]
set_property SLEW FAST [get_ports {sdram_a_o[7]}]
set_property SLEW FAST [get_ports {sdram_a_o[6]}]
set_property SLEW FAST [get_ports {sdram_a_o[5]}]
set_property SLEW FAST [get_ports {sdram_a_o[4]}]
set_property SLEW FAST [get_ports {sdram_a_o[3]}]
set_property SLEW FAST [get_ports {sdram_a_o[2]}]
set_property SLEW FAST [get_ports {sdram_a_o[1]}]
set_property SLEW FAST [get_ports {sdram_a_o[0]}]
set_property SLEW FAST [get_ports {sdram_ba_o[1]}]
set_property SLEW FAST [get_ports {sdram_ba_o[0]}]
set_property SLEW FAST [get_ports {sdram_dq_io[15]}]
set_property SLEW FAST [get_ports {sdram_dq_io[14]}]
set_property SLEW FAST [get_ports {sdram_dq_io[13]}]
set_property SLEW FAST [get_ports {sdram_dq_io[12]}]
set_property SLEW FAST [get_ports {sdram_dq_io[11]}]
set_property SLEW FAST [get_ports {sdram_dq_io[10]}]
set_property SLEW FAST [get_ports {sdram_dq_io[9]}]
set_property SLEW FAST [get_ports {sdram_dq_io[8]}]
set_property SLEW FAST [get_ports {sdram_dq_io[7]}]
set_property SLEW FAST [get_ports {sdram_dq_io[6]}]
set_property SLEW FAST [get_ports {sdram_dq_io[5]}]
set_property SLEW FAST [get_ports {sdram_dq_io[4]}]
set_property SLEW FAST [get_ports {sdram_dq_io[3]}]
set_property SLEW FAST [get_ports {sdram_dq_io[2]}]
set_property SLEW FAST [get_ports {sdram_dq_io[1]}]
set_property SLEW FAST [get_ports {sdram_dq_io[0]}]
set_property SLEW FAST [get_ports sdram_cas_n_o]
set_property SLEW FAST [get_ports sdram_cke_o]
set_property SLEW FAST [get_ports sdram_clk_o]
set_property SLEW FAST [get_ports sdram_cs_n_o]
set_property SLEW FAST [get_ports sdram_dqmh_o]
set_property SLEW FAST [get_ports sdram_dqml_o]
set_property SLEW FAST [get_ports sdram_ras_n_o]
set_property SLEW FAST [get_ports sdram_we_n_o]
set_property DRIVE 16 [get_ports {sdram_a_o[12]}]
set_property DRIVE 16 [get_ports {sdram_a_o[11]}]
set_property DRIVE 16 [get_ports {sdram_a_o[10]}]
set_property DRIVE 16 [get_ports {sdram_a_o[9]}]
set_property DRIVE 16 [get_ports {sdram_a_o[8]}]
set_property DRIVE 16 [get_ports {sdram_a_o[7]}]
set_property DRIVE 16 [get_ports {sdram_a_o[6]}]
set_property DRIVE 16 [get_ports {sdram_a_o[5]}]
set_property DRIVE 16 [get_ports {sdram_a_o[4]}]
set_property DRIVE 16 [get_ports {sdram_a_o[3]}]
set_property DRIVE 16 [get_ports {sdram_a_o[2]}]
set_property DRIVE 16 [get_ports {sdram_a_o[1]}]
set_property DRIVE 16 [get_ports {sdram_a_o[0]}]
set_property DRIVE 16 [get_ports {sdram_ba_o[1]}]
set_property DRIVE 16 [get_ports {sdram_ba_o[0]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[15]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[14]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[13]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[12]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[11]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[10]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[9]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[8]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[7]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[6]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[5]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[4]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[3]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[2]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[1]}]
set_property DRIVE 16 [get_ports {sdram_dq_io[0]}]
set_property DRIVE 16 [get_ports sdram_cas_n_o]
set_property DRIVE 16 [get_ports sdram_cke_o]
set_property DRIVE 16 [get_ports sdram_clk_o]
set_property DRIVE 16 [get_ports sdram_cs_n_o]
set_property DRIVE 16 [get_ports sdram_dqmh_o]
set_property DRIVE 16 [get_ports sdram_dqml_o]
set_property DRIVE 16 [get_ports sdram_ras_n_o]
set_property DRIVE 16 [get_ports sdram_we_n_o]

create_clock -period 10.000 [get_ports clk_i]